server:
  port: 9080

spring:
  application:
    name: ssi-verifier
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # required for the Swagger UI to work

keycloak:
  enabled: false
  auth-server-url: https://lissi-cloud-dev.westeurope.cloudapp.azure.com/auth
  realm: lissi-cloud
  resource: postman
  public-client: true
  securityConstraints:
    - authRoles: [ "lissi_manager" ]
      securityCollections:
        - patterns: [ "/*" ]
    - authRoles: [ ]
      securityCollections:
        - patterns: [ "/api/acapy-webhook/topic/*", "/stomp" ]

acapy:
  url: http://ssi-verifier-acapy:10000
  http-timeout-in-seconds: 60
  api-key: secret-key
  webhook-api-key: secret-key
