spring:
  thymeleaf:
    cache: false
  web:
    resources:
      chain:
        cache: false
  datasource:
    url: jdbc:postgresql://localhost:5432/controller
    username: controller
    password: controller

logging:
  level:
    root: WARN
    com.ssi.verifier: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO

keycloak:
  auth-server-url: http://keycloak.lissi-cloud.localhost:8080/auth

acapy:
  url: http://localhost:10000
  api-key:
  webhook-api-key: secret-key
