spring:
  thymeleaf:
    cache: false
  web:
    resources:
      chain:
        cache: false

keycloak:
  auth-server-url: http://keycloak.lissi-cloud.localhost:8080/auth

lissi-agent:
  url: http://localhost:9080/ctrl/api/v1.0
  tenant-id: test-agent

acapy:
  url: http://host-gateway:10000
  api-key:
  webhook-api-key: secret-key
