server:
  port: 9080
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false

spring:
  application:
    name: ssi-verifier
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # required for the Swagger UI to work
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/controller
    username: controller
    password: controller
  jpa:
    hibernate:
      ddl-auto: update

keycloak:
  enabled: false
  auth-server-url: https://lissi-cloud-dev.westeurope.cloudapp.azure.com/auth
  realm: lissi-cloud
  resource: postman
  public-client: true
  securityConstraints:
    - authRoles: [ "lissi_manager" ]
      securityCollections:
        - patterns: [ "/*" ]
    - authRoles: [ ]
      securityCollections:
        - patterns: [ "/api/acapy-webhook/topic/*", "/stomp" ]

acapy:
  url: http://ssi-verifier-acapy:10000
  http-timeout-in-seconds: 60
  api-key: secret-key
  webhook-api-key: secret-key
