spring:
  application:
    name: ssi-verifier
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # required for the Swagger UI to work

keycloak:
  auth-server-url: https://lissi-cloud-dev.westeurope.cloudapp.azure.com/auth
  realm: lissi-cloud
  resource: postman
  public-client: true
  securityConstraints:
    - authRoles: [ "lissi_manager" ]
      securityCollections:
        - patterns: [ "/*" ]

lissi-agent:
  url: https://lissi-cloud-dev.westeurope.cloudapp.azure.com/ctrl/api/v1.0
  tenant-id: default_tenant
