spring:
  thymeleaf:
    cache: false
  web:
    resources:
      chain:
        cache: false

keycloak:
  auth-server-url: http://keycloak.lissi-cloud.localhost:8080/auth

acapy:
  url: http://localhost:10000
  api-key:
  webhook-api-key: secret-key
