ssiVerifier:
  keycloakUrl: "https://DOMAIN.cloudapp.azure.com/auth"
  lissiAgentApiUrl: "https://DOMAIN.cloudapp.azure.com/ctrl/api/v1.0"
  tenantId: "default_tenant"
  k8sSecretRef: "ssi-verifier"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: DOMAIN
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: tls-secret
      hosts:
        - DOMAIN
