version: "3.7"
services:
  ssi-verifier-controller-db:
    container_name: ssi-verifier-controller-db
    image: ${POSTGRES_IMAGE}
    ports:
      - "5432:5432"
    volumes:
      - controller-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${CONTROLLER_DB_DATABASE_NAME}
      POSTGRES_USER: ${CONTROLLER_DB_USER}
      POSTGRES_PASSWORD: ${CONTROLLER_DB_PASSWORD}
    networks:
      - ssi-verifier-network
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "50m"
    restart: always

  ssi-verifier-acapy-db:
    container_name: ssi-verifier-acapy-db
    image: ${POSTGRES_IMAGE}
    ports:
      - "5433:5432"
    volumes:
      - acapy-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${ACAPY_DB_USER}
      POSTGRES_PASSWORD: ${ACAPY_DB_PASSWORD}
    networks:
      - ssi-verifier-network
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "50m"
    restart: always

  ssi-verifier-acapy:
    container_name: ssi-verifier-acapy
    image: ${ACAPY_IMAGE}
    entrypoint: /bin/bash
    command: [
      "-c",
      "sleep 10;
        aca-py start \
        --auto-provision
        --read-only-ledger
        --wallet-local-did
        --seed ${ACAPY_DID_SEED}
        --admin 0.0.0.0 10000 \
        --inbound-transport http 0.0.0.0 10001 \
        --outbound-transport http \
        --endpoint ${NGROK_PUBLIC_URL_ACAPY} \
        --genesis-file /genesis-file.txt \
        --ledger-pool-name ${ACAPY_LEDGER_NAME} \
        --invite-base-url didcomm://aries_connection_invitation \
        --admin-insecure-mode \
        --label ${ACAPY_LABEL} \
        --wallet-type askar \
        --wallet-name ${ACAPY_DB_DATABASE_NAME} \
        --wallet-key ${ACAPY_WALLET_KEY} \
        --wallet-storage-type postgres_storage \
        --wallet-storage-config '{\"url\":\"ssi-verifier-acapy-db:5432\",\"max_connections\":${ACAPY_MAX_DATABASE_CONNECTIONS}}' \
        --wallet-storage-creds '{\"account\":\"${ACAPY_DB_USER}\",\"password\":\"${ACAPY_DB_PASSWORD}\",\"admin_account\":\"${ACAPY_DB_USER}\",\"admin_password\":\"${ACAPY_DB_PASSWORD}\"}' \
        --auto-ping-connection \
        --auto-verify-presentation \
        --log-level INFO \
        --webhook-url http://host.docker.internal:9080/api/acapy-webhook#${CONTROLLER_WEBHOOK_API_KEY}
      "
    ]
    networks:
      - ssi-verifier-network
    ports:
      - "10000:10000" # Admin API
      - "10001:10001" # DIDcomm
    volumes:
      - ./acapy/genesis-files/${ACAPY_LEDGER_NAME}.txt:/genesis-file.txt:ro
    depends_on:
      - ssi-verifier-acapy-db
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "50m"
    restart: always

networks:
  ssi-verifier-network:
    name: ssi-verifier-network

volumes:
  acapy-db:
  controller-db:
